config/routes.rb
Rails.application.routes.draw do
  resources :themes
  root to: 'pages#index'

  devise_for :users

  resources :users, only: [:show]
  resources :events, except: [:destroy]
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos
  resources :events do
      resources :bookings, only: [:create]
    end

  namespace :api do
   resources :events, except: [:destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :themes
  has_many :photos
  has_many :bookings, dependent: :destroy
  has_many :guests, through: :bookings, source: :user

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  # validates :location, presence: true
  # validates :price, presence: true
  # validates :capacity, presence: true
  # validates :includes_food, presence: true
  # validates :includes_drinks, presence: true
  # validates :starts_at, presence: true, if: :starts_at < :ends_at
  # validates :ends_at, presence: true
  # validates :active, presence: true



end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_and_belongs_to_many :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_one :profile
  has_many :bookings, dependent: :destroy
  has_many :booked_events, through: :bookings, source: :event


  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/api/events_controller.rb
class Api::EventsController < ApplicationController
  def index
    render status: 200, json: {
      events: Event.all
    }.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def create
    @booking = current_user.bookings.create(booking_params)

    redirect_to @booking.event, notice: "Thank you for booking!"
  end

  private

  def booking_params
    params.require(:booking).permit(:price, :guests, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
   before_action :authenticate_user!, except: [:show]

   def index
     @events = current_user.events
   end

   def show
    @themes = @event.themes
    @photos = @event.photos
   end

   def new
     @event = current_user.events.build
   end

   def create
     @event = current_user.events.build(event_params)

     if @event.save
       image_params.each do |image|
      @event.photos.create(image: image)
      end
       #redirect_to edit_event_path(@event)
       redirect_to @event, notice: "Event created", notice: "Event created"
     else
       render :new
     end
   end

   def edit
     if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
 end

   def update
     if @event.update(event_params)
      image_params.each do |image|
        @event.photos.create(image: image)
      end

      redirect_to edit_event_path(@event), notice: "Room successfully updated"
     else
      render :edit
     end
   end

#used to order events
  def alphabetical
    order(ASC)
  end



   private

   def set_event
     @event = Event.find(params[:id])
   end

   def event_params
     params
       .require(:event)
       .permit(
       :name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, :created_at, :updated_at, theme_ids: []
       )
   end

    def image_params
      params[:images].present? ? params.require(:images) : []
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @event = photo.event
    if @event.user.id == current_user.id
      photo.destroy

      redirect_to edit_event_path(@event), notice: "Photo successfully removed"
    else
      redirect_to @event, notice: "Cannot delete that photo"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {multipart: true} do |f| %>

  <%= form_for @event do |f| %>
    <div class="form-group">
      <label>Event Name</label>
      <%= f.text_field :name, id: "name", prompt: "Type a name for your event", class: "form-input" %>

      <label>Event Description</label>
      <%= f.text_field :description, prompt: "What is it about? Describe in few words", class: "form-input" %>
    </div>
    <% @event.errors.full_messages.each %>

    <div class="form-group">
      <label>Number of People</label>
      <%= f.select :capacity, [["10", 1], ["< 10", 2], ["< 50", 3], ["< 100", 4], ["< 500", 5], ["1000+", 6]], prompt: "Select number of people that can attend the event", class: "form-control" %>
    </div>


    <div class="form-group">
       <label>Price</label>
       <div class="input-group">
         <div class="input-group-addon">€</div>
         <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
       </div>
     </div>

    <label>Amenities</label>

    <div class="form-group">
      <%= f.check_box :includes_food %> Food
    </div>
    <div class="form-group">
      <%= f.check_box :includes_drinks %> Drinks
    </div>

    <label>Themes</label>
    <%= f.collection_check_boxes(:theme_ids, Theme.all, :id, :name) do |b| %>
      <div class="form-group">
        <%= b.check_box(class: "check_box") %> <%= b.object.name %>
      </div>
    <% end %>

    <label>Photos</label>
    <div class="form-group">
      <span class="btn btn-default">
        Upload Photos
        <%= file_field_tag "images[]", type: :file, multiple: true %>
      </span>
      <div id="photos">
        <%= render 'photos/list' %>
      </div>
    </div>


    <div class="actions">
      <%= f.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", events_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", events_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new place", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<!-- bookings -->
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Book this event</div>

    <div class="panel-body">
      <%= render 'bookings/form' %>
    </div>
  </div>
<% end %>

<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>
  <div class="panel-body">

    <p>Location: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Event: <%= @event.name %></p>
    <p><%= @event.capacity %> <%= @event.capacity > 1 ? "Guests" : "Max Guest" %></p>
    <p><%= @event.price %> <%= @event.price > 1 ? "Price" : "Price" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("<s>Food</s>").html_safe : "Food" %></li>
      <li><%= !@event.includes_drinks ? ("<del>Food</del>").html_safe : "Drink" %></li>
    </ul>

    <!-- Themes -->
<h4>Themes</h4>
<% @themes.each do |theme| %>
  <span class="label label-success"><%= theme.name %></span>
<% end %>

<!-- Photos -->
<h4>Photos</h4>
<% @event.photos.each do |photo| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= image_tag photo.image.thumbnail %>
  </div>
</div>
<% end %>



</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>